(function(g){
"use strict";const W=g.Workshop,D=W.D,E=W.E,esc=W.esc;
const symbols=["↔","?","¼","a/b","↕","ƒ","∑","∧","↻","⌂","≠","t+1","[A]","→","rₜ","P","∫","±","r","Δ","κ","€","≤","[t)","✓","q<1","→","F","↻"];
function header(route){
 const active=route.startsWith("/course")||route.startsWith("/module")||route.startsWith("/lesson")||route.startsWith("/mission")?"course":route.startsWith("/lab")?"labs":route.startsWith("/glossary")?"glossary":"";
 return `<header class="site-header"><div class="header-inner"><a href="#/" class="brand" aria-label="Мастерская решений — главная"><span class="brand-mark" aria-hidden="true">∑</span><span>Мастерская решений</span></a>
 <nav class="main-nav ${W.state.menu?"open":""}" id="main-nav" aria-label="Главная навигация">${[["course","Курс"],["labs","Лаборатории"],["glossary","Глоссарий"]].map(([id,t])=>`<a href="#/${id}" class="${active===id?"active":""}" ${active===id?'aria-current="page"':""}>${t}</a>`).join("")}</nav>
 <div class="header-actions"><button class="icon-button" data-action="open-search" aria-label="Найти урок или понятие" title="Поиск · Ctrl+K">${g.icon("search")}</button><a class="btn btn-secondary btn-small session-link" href="#/session" title="Только текущий сеанс">Мой сеанс</a><button class="icon-button mobile-toggle" data-action="menu" aria-expanded="${W.state.menu}" aria-controls="main-nav" aria-label="Открыть меню">${g.icon("menu")}</button></div></div></header>`;
}
function footer(){return `<footer class="footer"><div class="container footer-inner"><span>Мастерская решений · Учебные примеры, реальные рассуждения</span><div class="footer-links"><a href="#/about">О курсе</a><a href="#/about/privacy">Без сохранений</a><a href="#/session">Мой сеанс</a></div></div></footer>`;}
function shell(html,route){return header(route)+html+footer();}
function crumbs(items){return `<nav class="breadcrumbs" aria-label="Путь">${items.map((x,i)=>`${i?g.icon("chevron"):""}${x[1]?W.link(x[1],x[0]):`<span>${esc(x[0])}</span>`}`).join("")}</nav>`;}
function home(){return `<main id="main" tabindex="-1" class="container"><section class="hero"><div><h1>Сложные идеи.<br><span>Понятные шаги.</span></h1><p class="lead">От первых чисел — к знакомству с моделями и алгоритмами. Разберите способ, измените условия и проверьте себя на новом примере.</p><div class="actions">${W.link("/lesson/M01.1","Начать с нуля","btn btn-primary","arrow")}${W.link("/course","Посмотреть курс","btn btn-secondary")}</div><p class="subnote">Без регистрации и оценки за скорость. Первые темы доступны с нуля; продвинутые опираются на предыдущие ступени.</p></div>
 <div class="hero-art"><div class="lab-top"><span>Попробуйте прямо здесь</span><span class="dots"><i></i><i></i><i></i></span></div><div class="demo-equation"><span class="demo-n">2</span><span>+</span><span class="demo-n">3</span><span>=</span><span class="demo-n answer" id="demo-result">?</span></div><div class="seat-strip">${Array.from({length:5},(_,i)=>`<span class="seat-visual ${i<2?"occupied":""}">${g.icon("chair")}</span>`).join("")}</div><p class="demo-question">Два места и ещё три. Сколько всего?</p><div class="demo-answers">${[4,5,6].map(n=>`<button type="button" data-demo="${n}" aria-label="Ответ ${n}">${n}</button>`).join("")}</div><div id="demo-feedback" class="demo-feedback" aria-live="polite">Начать можно с одного понятного действия.</div></div></section>
 <div class="home-divider"><div><strong>144</strong><p>урока с примером и тремя задачами</p></div><div><strong>${D.interactives.length}</strong><p>лабораторий, где можно действовать</p></div><div><strong>В своём темпе</strong><p>все темы открыты с первого шага</p></div></div>
 <section class="section"><div class="section-heading"><div><h2>Один путь. Шесть ступеней.</h2><p>Сначала — понятное действие. Затем — числа. И только потом — математическая запись.</p></div>${W.link("/course","Карта курса","btn btn-text","arrow")}</div><div class="stage-preview">${D.stages.map((s,i)=>`<article class="stage-mini"><span class="stage-index">${String(i+1).padStart(2,"0")}</span><h3>${s.title}</h3><p>${s.subtitle}</p>${W.link("/course/"+s.id,"Открыть ступень","","arrow")}</article>`).join("")}</div></section>
 <section class="feature-band"><div><h2>Формулу можно потрогать.</h2><p>Выбирайте слагаемые, считайте матрицы по строкам, открывайте будущее только после прогноза.</p></div>${W.link("/labs","В лаборатории","btn btn-lime","arrow")}</section>
 <section class="section" style="padding-bottom:50px"><div class="section-heading"><div><h2>Понять — значит суметь объяснить.</h2><p>Не только выбрать ответ: собрать решение, найти ошибку и применить знакомую идею в новых условиях.</p></div>${W.link("/practice","Смешанная практика","btn btn-secondary","target")}</div></section></main>`;}
function moduleRow(m){const k=W.completeCount(m.id);return `<a class="module-row" href="#/module/${m.id}"><span class="num">${String(m.number).padStart(2,"0")}</span><div><h3>${esc(m.title)}</h3><p>${esc(m.question)}</p>${k?`<div class="module-progress">${W.progress(k/6*100)}</div>`:""}</div><div class="row-end"><span>${k?k+" из 6":"6 уроков"}</span>${g.icon("arrow")}</div></a>`;}
function course(stage){const filter=stage||0;return `<main id="main" tabindex="-1" class="container page"><div class="page-intro"><h1>Карта курса</h1><p>Начните с первого шага или откройте нужную тему. У каждого модуля — шесть уроков и итоговая задача. В уроке четыре шага: объяснение, повторение способа, новое условие и самопроверка.</p></div><div class="filter-bar" aria-label="Ступени курса">${W.link("/course","Весь курс","filter "+(!filter?"active":""))}${D.stages.map(s=>W.link("/course/"+s.id,s.id+". "+s.title,"filter "+(filter===s.id?"active":""))).join("")}</div>
 ${D.stages.filter(s=>!filter||s.id===filter).map(s=>`<section class="course-stage"><div class="stage-info"><div class="number">${String(s.id).padStart(2,"0")}</div><h2>${s.title}</h2><p>${s.subtitle}</p></div><div>${D.modules.filter(m=>m.stage===s.id).map(moduleRow).join("")}</div></section>`).join("")}</main>`;}
function modulePage(id){const m=W.module(id);if(!m)return notFound();return `<main id="main" tabindex="-1" class="container page narrow">${crumbs([["Курс","/course"],[m.stageTitle,"/course/"+m.stage],[m.title]])}<div class="page-intro"><h1>${esc(m.title)}</h1><p>${esc(m.question)} ${esc(m.outcome)}</p></div><div class="actions">${W.link("/lesson/"+m.lessons[0],"Начать модуль","btn btn-primary","arrow")}${W.link("/mission/"+m.id,"К итоговой задаче","btn btn-secondary")}</div>
 <div class="module-lessons">${m.lessons.map((id,i)=>{const l=W.lesson(id),st=W.lessonStatus(id);return `<a class="lesson-row" href="#/lesson/${l.id}"><span class="lesson-number">${["transfer","assisted"].includes(st)?g.icon("check"):i+1}</span><div><h3>${esc(l.title)}</h3><div class="row-meta">${W.statusText(id)} · ${esc(W.lab(l.lab)?.displayTitle||"Практика")}</div></div>${g.icon("arrow")}</a>`;}).join("")}</div>
 <div class="feature-band"><div><h2>Теперь — новое условие</h2><p>${esc(D.missions.find(x=>x.module===id).title)}</p></div>${W.link("/mission/"+id,"Открыть задачу","btn btn-lime","arrow")}</div></main>`;}
function lessonPage(id,phase="learn"){
 const l=W.lesson(id);if(!l)return notFound();const m=W.module(l.module);W.state.lessons[id]=true;
 const tabs=[["learn","Разобраться"],["practice","Повторить способ"],["transfer","Новое условие"],["checkpoint","Самопроверка"]];
 if(!tabs.some(t=>t[0]===phase))return notFound();
 const idx=D.lessons.findIndex(x=>x.id===id),next=D.lessons[idx+1],status=W.lessonStatus(id),nextRoute=l.number===6?"/mission/"+m.id:next?"/lesson/"+next.id:"/session";
 let body="";
 if(phase==="learn")body=`<p class="explanation" id="lesson-explanation">${esc(l.explanation)}</p>${W.guideMarkup(l)}${l.formula?`<div class="lesson-example"><div class="label">Математическая запись</div>${W.formula(l)}</div>`:""}<div class="lesson-tools">${W.termMatches(l).map(t=>`<button class="term-chip" data-action="term" data-term="${esc(t.term)}">${esc(t.term)} ${g.icon("info")}</button>`).join("")}</div><div class="lab-goal"><h2>Исследуйте изменение условия</h2><p>${esc(W.lab(l.lab)?.description||l.action)}</p></div><div id="lesson-lab"></div><div class="lesson-bottom"><span class="muted">Сначала пример, затем действие и отдельная проверка.</span>${W.link("/lesson/"+id+"/practice","Повторить способ","btn btn-primary","arrow")}</div>`;
 else body=`${phase==="checkpoint"?`<div class="session-banner">Новый вариант отличается от разобранного примера. В результате отдельно учитываются первая проверка, исправления и помощь. Повторное открытие не стирает предыдущих попыток.</div>`:""}<div id="lesson-task"></div>${phase==="checkpoint"&&["transfer","assisted"].includes(status)?`<div class="complete-panel" style="margin-top:25px"><div class="complete-mark">${g.icon("check")}</div><h2>Три задания выполнены</h2><p>${status==="transfer"?"Новый вариант решён с первой проверки без раскрытия помощи. Это результат конкретного задания, не оценка владения всей темой.":"При выполнении нового варианта были исправления или помощь. Это часть обучения, а не повод снижать ценность проделанной работы."}</p>${W.link(nextRoute,l.number===6?"Итоговая задача":"Следующий урок","btn btn-primary","arrow")}</div>`:""}<div class="lesson-bottom">${W.link("/lesson/"+id,"К объяснению","btn btn-text","back")}${W.link(phase==="practice"?"/lesson/"+id+"/transfer":phase==="transfer"?"/lesson/"+id+"/checkpoint":nextRoute,phase==="practice"?"Новое условие":phase==="transfer"?"Самопроверка":"Дальше","btn btn-secondary","arrow")}</div>`;
 return `<main id="main" tabindex="-1" class="lesson-layout"><aside class="lesson-side">${W.link("/module/"+m.id,"К модулю","btn btn-text btn-small","back")}<div class="module-name">${esc(m.title)}</div>${W.progress(W.completeCount(m.id)/6*100)}<small class="muted">${W.completeCount(m.id)} из 6: три задания выполнены</small><nav aria-label="Уроки модуля">${m.lessons.map((lid,i)=>`<a href="#/lesson/${lid}" class="${lid===id?"active":""}" ${lid===id?'aria-current="page"':""}><span class="n">${["transfer","assisted"].includes(W.lessonStatus(lid))?"✓":i+1}</span><span>${esc(W.lesson(lid).title)}</span></a>`).join("")}</nav><div class="side-note">Все темы открыты. Возвращайтесь к предыдущему шагу, если трудно объяснить действие.<br><br>Ответы исчезнут после перезагрузки страницы.</div></aside><section class="lesson-main"><div class="lesson-head-top"><span class="step-label">Модуль ${m.number} · Урок ${l.number} из 6</span><button class="icon-button" data-action="speak" data-lesson="${id}" aria-label="Прочитать объяснение локальным голосом">${g.icon("sound")}</button></div><h1>${esc(l.title)}</h1><nav class="lesson-tabs" aria-label="Шаги урока">${tabs.map(([key,title],i)=>`<button class="${phase===key?"active":""}" data-action="lesson-phase" data-phase="${key}" data-lesson="${id}" ${phase===key?'aria-current="step"':""}><span class="stage-dot">${i+1}</span>${title}</button>`).join("")}</nav><div class="lesson-body">${body}</div></section></main>`;
}
function labsPage(){return `<main id="main" tabindex="-1" class="container page"><div class="page-intro"><h1>Лаборатории идей</h1><p>Здесь можно менять условия и видеть, что из этого следует. Все числа учебные, все опыты можно начать заново.</p></div><div class="glossary-search">${g.icon("search")}<input type="search" id="labs-filter" value="${esc(W.state.labQuery)}" placeholder="Матрица, прогноз, вероятность…" aria-label="Поиск лаборатории"></div><p class="muted" style="font-size:13px" id="labs-count"></p><div id="labs-list" class="lab-grid"></div></main>`;}
function labCard(t,i){return `<a href="#/lab/${t.id}" class="lab-card"><span class="lab-symbol" aria-hidden="true">${symbols[D.interactives.findIndex(x=>x.id===t.id)]||"∑"}</span><h3>${esc(t.displayTitle)}</h3><p>${esc(t.description)}</p><div class="card-bottom"><span>Исследовать</span>${g.icon("arrow")}</div></a>`;}
function labPage(id){const lab=W.lab(id);if(!lab)return notFound();const lessons=D.lessons.filter(l=>l.lab===id);return `<main id="main" tabindex="-1" class="container page">${crumbs([["Лаборатории","/labs"],[lab.displayTitle]])}<div class="page-intro"><h1>${esc(lab.displayTitle)}</h1><p>${esc(lab.description)}</p></div><div class="lab-layout"><div id="lab-mount"></div><aside class="lab-aside"><div><h3>Что здесь изучаем</h3><p>${esc(lab.skills)}</p>${lessons.slice(0,4).map(l=>`<a class="search-result" href="#/lesson/${l.id}">${esc(l.title)} ${g.icon("chevron")}</a>`).join("")}</div><div class="note"><h3>Типичная ошибка</h3><p>${esc(lab.error||"Смысл и условия вычисления важнее одного полученного числа.")}</p><p>Опыт не даёт отметку за знание. Самостоятельные задачи находятся в уроках.</p>${W.link("/glossary","Открыть глоссарий","btn btn-text","book")}</div></aside></div></main>`;}

function glossaryPage(){return `<main id="main" tabindex="-1" class="container page"><div class="page-intro"><h1>Глоссарий без сложных слов</h1><p>Не нужно заучивать весь список. Найдите понятие, посмотрите на пример и вернитесь к действию.</p></div><div class="glossary-search">${g.icon("search")}<input type="search" id="glossary-filter" value="${esc(W.state.glossaryQuery)}" placeholder="Например, сумма или матрица" aria-label="Поиск понятия"></div><p id="glossary-count" class="muted" style="font-size:13px"></p><div id="glossary-list" class="glossary-results"></div></main>`;}
function termCard(t){return `<article class="glossary-term"><h3>${esc(t.term)}</h3><p>${esc(t.definition)}</p><p class="example">${esc(t.example)}</p>${W.link("/module/"+t.module,"К теме в курсе","","arrow")}</article>`;}
function aboutPage(){return `<main id="main" tabindex="-1" class="container page narrow prose"><div class="page-intro"><h1>Понимать, а не угадывать</h1><p>Мастерская решений — открытый курс математики, моделей и алгоритмов на примерах учебного кампуса.</p></div>
 <h2>Кому адресован курс</h2><p>Первые модули вводят базовые действия. Для сложных разделов нужны освоенные доли, алгебра, векторы и вероятности. Продвинутые уроки дают первое знакомство, а не полное обучение исследовательскому применению методов. Темп и доступность для конкретного возраста требуют проверки с учащимися.</p><h2>Как проходить курс</h2><p>Каждый модуль состоит из шести коротких уроков. Сначала разберите идею и попробуйте интерактив. Затем повторите способ, перенесите его на другое условие и выполните третье задание для самопроверки. Итоговая миссия соединяет несколько навыков. В модуле 24 доступен связанный проект с заключением: программа проверяет предусмотренные числа и основания, текст оценивает преподаватель или сам учащийся по открытым критериям.</p>
 <p>Никаких жизней, платных попыток, рейтинга людей и оценки за скорость. Любой урок можно открыть сразу. Когда становится трудно, вернитесь к понятному шагу.</p>
 <h2>Что означает результат</h2><p>Урок отмечается выполненным после трёх заданий. Отдельно показывается, решён ли новый вариант с первой проверки без помощи. Если были исправления или раскрыт разбор, это отражается в отметке. Повторение разобранного примера не называется самостоятельным владением темой. Результаты смешанной практики считаются отдельно для каждого захода, без зачёта прежних ответов. Эти отметки не удостоверяют профессиональную квалификацию.</p>
 <h2>Без аккаунтов и сохранений</h2><p>Ответы не сохраняются автоматически на устройстве и не отправляются на сервер. В итоговой мастерской текст работы можно явно выгрузить в файл собственной кнопкой; только в этом случае создаётся файл на устройстве. Аккаунтов здесь нет. Результаты хранятся только в памяти открытой страницы. После перезагрузки они исчезают. Можно добавить обычную закладку на нужный урок, но ответы в ней не сохраняются.</p>
 <p>В составе приложения нет аналитических трекеров, рекламы, внешних шрифтов и сетевых библиотек. Ссылки на источники открываются только по вашему нажатию.</p>
 <h2>Управление и озвучивание</h2><p>Действия доступны кнопками и полями ввода, без обязательного перетаскивания. Используйте Tab для перехода, Enter и пробел — для нажатия. Escape закрывает окно поиска и словаря. Движение учитывает настройку уменьшения анимации.</p>
 <p>Кнопка озвучивания использует только локальный русский голос, если он доступен на устройстве. Если такого голоса нет, приложение сообщает об этом и оставляет текст на экране. Записанная дикторская озвучка в эту версию не входит.</p>
 <h2>Учебная модель — не наблюдение</h2><p>Кампус и числовые случаи условны. Правильный расчёт модели не доказывает её соответствия реальному объекту. В курсе отдельно рассматриваются источник данных, сравнимость, неопределённость и допустимые границы выводов.</p>
 <h2>Педагогические и методические ориентиры</h2><p>Короткий разобранный пример, самостоятельное действие, возвращение к изученному и перенос в новую задачу. Источники ниже объясняют используемые принципы. Они не являются подтверждением эффективности именно этого курса.</p>
 ${D.sources.map(s=>`<article style="padding:18px 0;border-bottom:1px solid var(--line)"><h3 style="font-size:18px">${esc(s.title)}</h3><p style="font-size:13px;margin:7px 0">${esc(s.author)} · ${esc(s.year)}</p><p style="font-size:14px">${esc(s.use)}</p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer" style="font-size:13px">Открыть источник ${g.icon("external")}</a><details class="help-disclosure"><summary>Границы применения</summary><p style="font-size:13px;margin-top:10px">${esc(s.limits)}</p></details></article>`).join("")}
 <h2>Готовность курса</h2><p>В этой версии материалы и алгоритмы доступны для прохождения. Версия 1.1.0. Учебная результативность не измерена на выборке пользователей; курс не обещает одинаковый темп или одинаковый итог людям разного возраста и опыта.</p></main>`;}
function sessionPage(){const st=W.totalStatus(),opened=Object.keys(W.state.lessons).length;return `<main id="main" tabindex="-1" class="container page narrow"><div class="page-intro"><h1>Ваш текущий сеанс</h1><p>Здесь видны действия только в этой открытой странице. После её перезагрузки история исчезнет.</p></div><div class="stat-line"><div><strong>${opened}</strong><span>уроков открыто</span></div><div><strong>${st.completed}</strong><span>разобрано</span></div><div><strong>${st.independent}</strong><span>новый вариант с первой проверки</span></div></div>
 ${opened?D.modules.filter(m=>m.lessons.some(id=>W.state.lessons[id])).map(m=>`<section style="margin-bottom:24px"><h3 style="margin-bottom:14px">${esc(m.title)}</h3>${m.lessons.filter(id=>W.state.lessons[id]).map(id=>`<a class="module-row" href="#/lesson/${id}"><span>${g.icon(["transfer","assisted"].includes(W.lessonStatus(id))?"check":"book")}</span><span>${esc(W.lesson(id).title)}</span><small class="muted">${W.statusText(id)}</small></a>`).join("")}</section>`).join(""):`<div class="empty-state"><h2>Первый шаг ещё впереди</h2><p>Начните с предметов и чисел — никаких знаний заранее не нужно.</p>${W.link("/lesson/M01.1","Начать","btn btn-primary","arrow")}</div>`}
 <div class="session-banner">Открытие интерактива не считается доказательством понимания. Результат задачи с подсказкой не превращается в самостоятельный при повторном открытии.</div><div class="actions">${W.link("/practice","Смешанная практика","btn btn-primary","target")}${W.btn("Начать новый сеанс","reset-session","btn btn-secondary")}</div></main>`;}
function missionPage(mid,step=0){const m=D.missions.find(x=>x.module===mid);if(!m)return notFound();const module=W.module(mid),done=m.tasks.every(id=>W.state.tasks[id]?.correct),helped=m.tasks.some(id=>W.state.tasks[id]?.helped);
 return `<main id="main" tabindex="-1" class="container page narrow">${crumbs([["Курс","/course"],[module.title,"/module/"+mid],["Итоговая задача"]])}<div class="page-intro"><h1>${esc(m.title)}</h1><p>${esc(m.prompt)}</p></div>
 <div class="session-banner"><strong>Задача:</strong> ${esc(m.action)}</div>${m.tasks.length>1?`<div class="filter-bar">${m.tasks.map((id,i)=>W.link("/mission/"+mid+"/"+i,i===0?"Расчёт":"Основание","filter "+(i===step?"active":""))).join("")}</div>`:""}<div id="mission-task"></div>
 ${done?`<div class="complete-panel" style="margin-top:28px"><div class="complete-mark">${g.icon("check")}</div><h2>${helped?"Миссия разобрана с помощью":"Миссия выполнена"}</h2><p>${esc(m.answer)}</p><div class="actions">${W.link(module.number<24?"/module/M"+String(module.number+1).padStart(2,"0"):"/session",module.number<24?"Следующий модуль":"Посмотреть сеанс","btn btn-primary","arrow")}</div></div>`:""}</main>`;}
function practicePage(){const p=W.state.practice;
 if(!p)return `<main id="main" tabindex="-1" class="container page narrow"><div class="page-intro"><h1>Соединяем знакомые идеи</h1><p>Восемь задач из разных уроков. Без времени на ответ. Выберите ступени, к которым готовы.</p></div><div class="options">${[["1","Первые шаги · модули 1–4"],["2","Системы и связи · модули 5–12"],["3","Модели и решения · модули 13–20"],["4","Проверка и мастерство · модули 21–24"],["5","Весь курс"]].map(([id,title])=>`<button class="option" data-action="start-practice" data-range="${id}">${g.icon("target")} ${title} ${g.icon("arrow")}</button>`).join("")}</div><div class="session-banner">В практике используются новые для текущего сеанса условия, когда они доступны. Это учебное повторение, не официальный экзамен.</div></main>`;
 if(p.index>=p.ids.length){const stats=E.practiceStats(p),correct=stats.correct,help=stats.helped;return `<main id="main" tabindex="-1" class="container page narrow"><div class="complete-panel"><div class="complete-mark">${g.icon("check")}</div><h1>Практика завершена</h1><p>В этом заходе решено ${correct} из ${p.ids.length}. Без отправки ответа: ${stats.skipped}. С первой проверки без помощи: ${stats.first}. Помощь использована в ${help} задачах. Прежние ответы не засчитываются.</p><div class="actions">${W.btn("Другой набор","new-practice","btn btn-primary","", "reset")}${W.link("/course","Вернуться к курсу","btn btn-secondary")}</div></div>${p.ids.map(id=>{const t=W.task(id),l=W.lesson(t.lesson);return `<a class="module-row" href="#/lesson/${l.id}"><span>${p.results[id]?.correct?g.icon("check"):g.icon("book")}</span><span>${esc(l.title)}</span><small>${p.results[id]?.helped?"С помощью":p.results[id]?.correct?"Верно":"Повторить"}</small></a>`;}).join("")}</main>`;}
 const t=W.task(p.ids[p.index]),l=W.lesson(t.lesson);return `<main id="main" tabindex="-1" class="container page narrow"><div class="page-intro"><h1>Задача ${p.index+1} из ${p.ids.length}</h1><p>${esc(l.title)}</p></div>${W.progress(p.index/p.ids.length*100)}<div id="practice-task" style="margin-top:25px"></div><div class="lesson-bottom">${`<a href="#/lesson/${l.id}" class="btn btn-text" data-action="practice-refresher">Повторить идею ${g.icon("book")}</a>`}${W.btn("Пропустить и продолжить","practice-next","btn btn-secondary")}</div></main>`;}
function notFound(){return `<main id="main" tabindex="-1" class="container page"><div class="empty-state"><h1>Такой страницы нет</h1><p>Карта курса поможет найти нужную тему.</p>${W.link("/course","Открыть курс","btn btn-primary","arrow")}</div></main>`;}
function renderCollections(){
 const li=document.getElementById("labs-list");if(li){
 const update=()=>{const q=W.state.labQuery.toLowerCase().trim(),a=D.interactives.filter(t=>(t.displayTitle+" "+t.description+" "+t.skills).toLowerCase().includes(q));li.innerHTML=a.map(labCard).join("")||'<div class="empty-state">Лаборатория не найдена. Попробуйте другое слово.</div>';document.getElementById("labs-count").textContent=`Найдено: ${a.length} из ${D.interactives.length}`;};
 document.getElementById("labs-filter").oninput=e=>{W.state.labQuery=e.target.value;update();};update();
 }
 const gl=document.getElementById("glossary-list");if(gl){
 const update=()=>{const q=W.state.glossaryQuery.toLowerCase().trim(),a=D.glossary.filter(t=>(t.term+" "+t.definition+" "+t.example).toLowerCase().includes(q));gl.innerHTML=a.map(termCard).join("")||'<div class="empty-state">Понятие не найдено. Попробуйте более короткое слово.</div>';document.getElementById("glossary-count").textContent=`Найдено: ${a.length} из ${D.glossary.length}`;};
 document.getElementById("glossary-filter").oninput=e=>{W.state.glossaryQuery=e.target.value;update();};update();
 }
}
W.render=function(focus=true){
 try{
 W.cleanup?.();W.cleanup=null;W.state.menu=false;
 if(document.getElementById("overlay").children.length)W.closeDialog();
 if("speechSynthesis"in window)speechSynthesis.cancel();
 let route=location.hash.slice(1)||"/";if(route==="main")route="/";
 const parts=route.split("/").filter(Boolean),kind=parts[0]||"home";let html="";
 switch(kind){case"home":html=home();break;case"course":html=course(Number(parts[1])||0);break;case"module":html=modulePage(parts[1]);break;case"lesson":html=lessonPage(parts[1],parts[2]||"learn");break;case"labs":html=labsPage();break;case"lab":html=labPage(parts[1]);break;case"glossary":html=glossaryPage();break;case"about":html=aboutPage();break;case"session":html=sessionPage();break;case"mission":html=missionPage(parts[1],Number(parts[2])||0);break;case"practice":html=practicePage();break;default:html=notFound();}
 document.getElementById("app").innerHTML=shell(html,route);
 const h=document.querySelector("main h1");document.title=(h?.innerText||"Главная").replace(/\s+/g," ")+" · Мастерская решений";
 renderCollections();
 if(kind==="lesson"){
 const l=W.lesson(parts[1]);if(l){
 const phase=parts[2]||"learn";
 if(phase==="learn")W.mountLab(document.getElementById("lesson-lab"),l.lab,{inline:true,lesson:l});
 else if(["practice","transfer","checkpoint"].includes(phase)){const t=W.task(l.id+(phase==="practice"?"-A":phase==="transfer"?"-B":"-C"));W.mountTask(document.getElementById("lesson-task"),t,{nextLabel:phase==="practice"?"К новому условию":null,onNext:()=>W.go("/lesson/"+l.id+"/transfer"),onCheck:ok=>{if(ok)W.render(false);}});}
 }}
 if(kind==="lab"&&W.lab(parts[1]))W.mountLab(document.getElementById("lab-mount"),parts[1]);
 if(kind==="mission"){const m=D.missions.find(x=>x.module===parts[1]),step=Number(parts[2])||0;if(m&&m.tasks[step])W.mountTask(document.getElementById("mission-task"),W.task(m.tasks[step]),{nextLabel:step<m.tasks.length-1?"Проверить основание":null,onNext:()=>W.go("/mission/"+m.module+"/"+(step+1)),onCheck:ok=>{if(ok)W.render(false);}});}
 if(kind==="practice"&&W.state.practice){const p=W.state.practice;if(p.index<p.ids.length)W.mountTask(document.getElementById("practice-task"),W.task(p.ids[p.index]),{store:p.results,nextLabel:"Следующая задача",onNext:()=>{p.index++;W.render();}});}
 if(focus){window.scrollTo(0,0);requestAnimationFrame(()=>document.getElementById("main")?.focus({preventScroll:true}));}
 }catch(err){console.error(err);document.getElementById("app").innerHTML=header("")+`<main id="main" class="error-boundary"><h1>Не удалось открыть страницу</h1><p>Вернитесь к карте курса. Уже выполненные в этом сеансе задачи сохранятся в памяти страницы.</p>${W.link("/course","Карта курса","btn btn-primary")}</main>`;}
};
document.addEventListener("click",e=>{
 const skip=e.target.closest(".skip-link");if(skip){e.preventDefault();document.getElementById("main")?.focus();return;}
 const demo=e.target.closest("[data-demo]");if(demo){const correct=+demo.dataset.demo===5;document.getElementById("demo-result").textContent=correct?"5":"?";document.getElementById("demo-feedback").textContent=correct?"Верно. Пять мест — пять стульев. Уже первый шаг.":"Посчитайте все пять стульев под записью.";return;}
 const el=e.target.closest("[data-action]");if(!el){if(e.target.closest("#overlay a[href^='#/']"))W.closeDialog();return;}
 switch(el.dataset.action){
 case"open-search":W.openSearch();break;
 case"close-dialog":W.closeDialog();break;
 case"backdrop":if(e.target===el)W.closeDialog();break;
 case"term":W.openTerm(el.dataset.term);break;
 case"menu":W.state.menu=!W.state.menu;document.getElementById("main-nav").classList.toggle("open",W.state.menu);el.setAttribute("aria-expanded",String(W.state.menu));break;
 case"lesson-phase":W.go("/lesson/"+el.dataset.lesson+"/"+el.dataset.phase);break;
 case"speak":{const l=W.lesson(el.dataset.lesson);W.speak(l.title+". "+l.explanation+" "+(l.guide?.bridge||""));break;}
 case"reset-session":W.openDialog("Начать заново?",`<p>Все ответы и отметки текущего сеанса будут очищены. Учебные материалы останутся доступными.</p><div class="actions">${W.btn("Да, очистить","confirm-reset","btn btn-primary")}${W.btn("Вернуться","close-dialog","btn btn-secondary")}</div>`);break;
 case"confirm-reset":W.state.tasks={};W.state.lessons={};W.state.missions={};W.state.labRuns={};W.state.practice=null;W.state.notes={};W.state.capstone=null;W.closeDialog();W.render();break;
 case"start-practice":{
 const range=el.dataset.range,limits={1:[1,4],2:[5,12],3:[13,20],4:[21,24],5:[1,24]}[range]||[1,24];
 const candidates=D.tasks.filter(t=>{const n=+t.lesson.slice(1,3);return n>=limits[0]&&n<=limits[1]});
 const fresh=candidates.filter(t=>!W.state.tasks[t.id]?.correct),old=candidates.filter(t=>W.state.tasks[t.id]?.correct);
 const shuffled=[...E.shuffled(fresh,Date.now()%100000),...E.shuffled(old,Date.now()%90000)];
 W.state.practice={ids:shuffled.slice(0,8).map(t=>t.id),index:0,results:{}};W.render();break;}
 case"practice-refresher":{const p=W.state.practice;if(p&&p.index<p.ids.length){const id=p.ids[p.index];(p.results[id]||(p.results[id]={})).helped=true;}break;}
 case"practice-next":if(W.state.practice){W.state.practice.index++;W.render();}break;
 case"new-practice":W.state.practice=null;W.render();break;
 }
});
window.addEventListener("hashchange",()=>W.render());
W.render();
})(globalThis);
